export const onRenderBody = ({ setHeadComponents }) => {
  setHeadComponents([
    <link
      rel='preload'
      href='/fonts/SourceSans3VF-Roman.woff2'
      as='font'
      type='font/woff2'
      crossOrigin='anonymous'
      key='SourceSans3VF-Roman'
    />,
    <link
      rel='preload'
      href='/fonts/SourceSans3VF-Italic.woff2'
      as='font'
      type='font/woff2'
      crossOrigin='anonymous'
      key='SourceSans3VF-Roman'
    />,
    <link
      rel='preload'
      href='/fonts/RobotoMono-Italic-VariableFont_wght.woff'
      as='font'
      type='font/woff'
      crossOrigin='anonymous'
      key='RobotoMono-Italic-VariableFont_wght.woff'
    />,
    <link
      rel='preload'
      href='/fonts/RobotoMono-Italic-VariableFont_wght.woff2'
      as='font'
      type='font/woff2'
      crossOrigin='anonymous'
      key='RobotoMono-Italic-VariableFont_wght.woff2'
    />,
    <link
      rel='preload'
      href='/fonts/RobotoMono-VariableFont_wght.woff'
      as='font'
      type='font/woff'
      crossOrigin='anonymous'
      key='RobotoMono-VariableFont_wght.woff'
    />,
    <link
      rel='preload'
      href='/fonts/RobotoMono-VariableFont_wght.woff2'
      as='font'
      type='font/woff2'
      crossOrigin='anonymous'
      key='RobotoMono-VariableFont_wght.woff2'
    />
  ])
}
